/* Lógico_VibeLeve: */

CREATE TABLE CLIENTE (
    Email_Cliente VARCHAR,
    Nome_Cliente VARCHAR,
    Sobrenome_Cliente VARCHAR,
    Telefone_Cliente VARCHAR,
    Endereco VARCHAR,
    CPF VARCHAR PRIMARY KEY
);

CREATE TABLE PACOTES (
    Tipo_hospedagem VARCHAR,
    Cód_Destino VARCHAR PRIMARY KEY,
    Nome_Destinos VARCHAR,
    Qtde_vagas VARCHAR
);

CREATE TABLE COMPRAR (
    FK_PACOTES_Cód_Destino VARCHAR PRIMARY KEY,
    FK_CLIENTE_CPF VARCHAR
);
 
ALTER TABLE COMPRAR ADD CONSTRAINT FK_COMPRAR_1
    FOREIGN KEY (FK_PACOTES_Cód_Destino)
    REFERENCES PACOTES (Cód_Destino)
    ON DELETE SET NULL;
 
ALTER TABLE COMPRAR ADD CONSTRAINT FK_COMPRAR_2
    FOREIGN KEY (FK_CLIENTE_CPF)
    REFERENCES CLIENTE (CPF)
    ON DELETE SET NULL;